CREATE TABLE Person (
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE,
    birth_year int CHECK(birth_year>1900)
);
CREATE TABLE Book (
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int references Person(person_id) ON DELETE SET NULL,
    name varchar NOT NULL,
    author varchar NOT NULL,
    year int
);

ALTER TABLE Book ADD COLUMN taken_at timestamp;
UPDATE Book SET taken_at='2023-09-01 10:00:00' WHERE book_id=4;