CREATE TABLE Person (
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE,
    birth_year int CHECK(birth_year>1900)
);
CREATE TABLE Book (
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int references Person(person_id) ON DELETE SET NULL,
    name varchar NOT NULL,
    author varchar NOT NULL,
    year int
);